### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by DogsTailFarmer** [DogsTailFarmer/binance.py#23]
ver: 1.3.5rc2

```
[2023-08-12 19:25:41,541: WARNING] OpenClientConnection for 'BitfinexSub5' exception: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2023-08-12 19:25:41,546: DEBUG] Exception traceback: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/exch_srv.py", line 159, in OpenClientConnection
    await open_client.client.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/client.py", line 104, in load
    infos = await self.fetch_exchange_info()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/client.py", line 287, in fetch_exchange_info
    binance_res = bfx.exchange_info(symbols_details, tickers)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/bitfinex_parser.py", line 101, in exchange_info
    _tick_size = tick_size(market.get('price_precision'), _price)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/bitfinex_parser.py", line 64, in tick_size
    x = int(_price)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by DogsTailFarmer** [comment]
Reason - can't getting exchange info from Bitfinex. It's resolved himself.
```
[2023-08-12 19:25:41,550: ERROR] Exception on register client: RESOURCE_EXHAUSTED, int() argument must be a string,
a bytes-like object or a real number, not 'NoneType'
[2023-08-12 19:25:41,550: INFO] Restart gRPC client session
12/08 19:25:42 Exception buffered_orders: Send gRPC request failed, not active client session
[2023-08-12 19:25:50,860: INFO] gRPC session started for client_id: 140449909220944
trade_id: amtiJJmFpgxVHjuuGH632H
12/08 19:25:50 Init WSS, client_id: 140449909220944
12/08 19:25:52 Trying restore saved state after lost connection to host
```
