### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by DogsTailFarmer** [DogsTailFarmer/binance.py#24]
ver: 1.3.5rc2

```
[2023-08-12 19:26:34,063: ERROR] FetchKlines for LTCUST interval: 1m, exception: 'NoneType' object has no attribute 'get'
[2023-08-12 19:26:34,064: ERROR] Unexpected [AttributeError] raised by servicer method [/martin.Martin/OnTickerUpdate]
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 682, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 809, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 580, in _handle_unary_stream_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 495, in _finish_handler_with_stream_responses
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/exch_srv.py", line 556, in OnTickerUpdate
    _symbol = client.symbol_to_bfx(request.symbol)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/exchanges_wrapper/client.py", line 186, in symbol_to_bfx
    base_asset = symbol_info.get('baseAsset')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by DogsTailFarmer** [comment]
When downloading data from Bitfinex, a false-positive signal was obtained about a successful download in all cases. Fixed in 1.3.5rc3
